##  This file contains two functions that are used to create an object that 
##  stores a square matrix and cache's its inverse (assuming that the matrix is a 
##  square invertible matrix). This should cut down on time when the need to compute the inverse 
##  of a large square matrice repeatedly occurs. 

## makeCacheMatrix is a function that stores a list of four functions that are used to 
## set the matrix if need be (not required), return the matrix that is currently stored, 
## store the value of the value of whatever has been input into variable m into the 
## overall function, and return I. The four functions are stored in a list so that we can 
## assign one object that contains all four functions.

makeCacheMatrix <- function(x = matrix()) {
  I<-NULL
  set<-function(y){
    x<<-y
    I<<-NULL
  }
  get<-function() x
  setmatrix<-function(inverse) I<<- inverse
  getmatrix<-function() I
  list(set=set, get=get,
       setmatrix=setmatrix,
       getmatrix=getmatrix)
}


## cachemean is a function that first assesses whether there is a stored 
## matrix (non null) called I which would have been previously stored by the getmatrix 
## function. If this matrix is still in existence the cachemean function returns 
## the previosuly stored matrix (I) and stops computing. If there is no non null matrix 
## called I then the function called data gets the matrix stored by running makeCacheMatrix
## The function I calculates the inverse of the matrix using the solve function and the 
## inverse is stored in the object generated by setmatrix in makeCacheMatrix. 

cacheSolve <- function(x=matrix(), ...) {
  I<-x$getmatrix()
  if(!is.null(I)){
    message("getting cached inverse")
    return(I)
  }
  data<-x$get()
  I<-solve(data, ...)
  x$setmatrix(I)
  I
}